/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author ramir
 */
public class PantallaMenu extends javax.swing.JPanel {

    VentanaPrincipal ventanaPrincipal;
    
    /**
     * Creates new form PantallaMenu
     */
    public PantallaMenu(VentanaPrincipal ventanaPrincipal) {
        initComponents();
        this.ventanaPrincipal = ventanaPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonOfertas = new javax.swing.JButton();
        buttonResumenOfertas = new javax.swing.JButton();

        buttonOfertas.setText("Ofertas");
        buttonOfertas.addActionListener(this::buttonOfertasActionPerformed);

        buttonResumenOfertas.setText("Resumen Ofertas");
        buttonResumenOfertas.addActionListener(this::buttonResumenOfertasActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonResumenOfertas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonOfertas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(268, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(buttonOfertas)
                .addGap(47, 47, 47)
                .addComponent(buttonResumenOfertas)
                .addContainerGap(257, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOfertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOfertasActionPerformed
        // TODO add your handling code here:
        ventanaPrincipal.mostrarPantalla("ofertas");
    }//GEN-LAST:event_buttonOfertasActionPerformed

    private void buttonResumenOfertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResumenOfertasActionPerformed
        // TODO add your handling code here:
        ventanaPrincipal.mostrarPantalla("listadoOfertas");
    }//GEN-LAST:event_buttonResumenOfertasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonOfertas;
    private javax.swing.JButton buttonResumenOfertas;
    // End of variables declaration//GEN-END:variables
}
