/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import database.Oferta;
import database.Postulante;
import database.Producto;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author ramir
 */
public class PantallaOfertas extends javax.swing.JPanel implements IPantallaBase {

    VentanaPrincipal ventanaPrincipal;
    
    /**
     * Creates new form PantallaOfertas
     */
    public PantallaOfertas(VentanaPrincipal ventanaPrincipal) {
        initComponents();
        this.ventanaPrincipal = ventanaPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonVolver = new javax.swing.JButton();
        comboProducto = new javax.swing.JComboBox<>();
        comboPostulante = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textMonto = new javax.swing.JTextField();
        buttonRegistrarOferta = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        buttonVolver.setText("Volver");
        buttonVolver.addActionListener(this::buttonVolverActionPerformed);

        comboProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboPostulante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Producto");

        jLabel2.setText("Postulante");

        buttonRegistrarOferta.setText("Registrar oferta");
        buttonRegistrarOferta.addActionListener(this::buttonRegistrarOfertaActionPerformed);

        jLabel3.setText("Monto de la oferta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonVolver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(comboProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboPostulante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textMonto))
                                .addGap(20, 20, 20)
                                .addComponent(buttonRegistrarOferta)))
                        .addGap(0, 159, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboPostulante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRegistrarOferta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(buttonVolver)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRegistrarOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegistrarOfertaActionPerformed
        Oferta oferta = new Oferta();
        DefaultComboBoxModel modelPostulante = (DefaultComboBoxModel) comboPostulante.getModel();
        DefaultComboBoxModel modelProducto = (DefaultComboBoxModel) comboProducto.getModel();
        
        if(modelPostulante.getSelectedItem() == null || modelProducto.getSelectedItem() == null){
            System.out.println("Debe seleccionar un item y un postulanate");
            return;
        }
        
        try {
            String texto = textMonto.getText().trim().replace(",", ".");
            BigDecimal monto = new BigDecimal(texto);
            oferta.setMonto(monto);
        } catch (NumberFormatException ex) {
            System.out.println("Error: el monto no es válido");
            return;
        }
      
        oferta.setDniPostulante((Postulante) modelPostulante.getSelectedItem());
        oferta.setIdProducto((Producto) modelProducto.getSelectedItem());
        oferta.setFechaCreacion(LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")));
        
        if(oferta.getIdProducto().getPrecioBase().doubleValue() > oferta.getMonto().doubleValue()){
            System.out.println("El monto a ofertar debe ser mayor al precio base");
            return;
        }
        
        oferta.setEstado(oferta.validaMontoSincronizado(oferta.getMonto(), oferta.getIdProducto().getId()));
        
        oferta.registrarOfertaSincronizada(oferta);
        
        modelPostulante.setSelectedItem(null);
        modelProducto.setSelectedItem(null);
        textMonto.setText("");
        
    }//GEN-LAST:event_buttonRegistrarOfertaActionPerformed

    private void buttonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVolverActionPerformed
        // TODO add your handling code here:
        ventanaPrincipal.mostrarPantalla("menu");
    }//GEN-LAST:event_buttonVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonRegistrarOferta;
    private javax.swing.JButton buttonVolver;
    private javax.swing.JComboBox<String> comboPostulante;
    private javax.swing.JComboBox<String> comboProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField textMonto;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onShow() {
        DefaultComboBoxModel productoModel = (DefaultComboBoxModel) comboProducto.getModel();
        DefaultComboBoxModel postulanteModel = (DefaultComboBoxModel) comboPostulante.getModel();
        
        productoModel.removeAllElements();
        productoModel.addAll(Producto.obtenerTodos());
        
        postulanteModel.removeAllElements();
        postulanteModel.addAll(Postulante.obtenerTodos());
        
    }
}
