/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import database.Oferta;
import database.Postulante;
import database.Producto;
import javax.swing.table.DefaultTableModel;
import thread.OferenteProcessor_Thread;

/**
 *
 * @author ramir
 */
public class PantallaListadoOfertas extends javax.swing.JPanel implements IPantallaBase{

    VentanaPrincipal ventanaPrincipal;
    
    /**
     * Creates new form PantallaListadoOfertas
     */
    public PantallaListadoOfertas(VentanaPrincipal ventanaPrincipal) {
        initComponents();
        this.ventanaPrincipal = ventanaPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableOfertas = new javax.swing.JTable();
        buttonVolver = new javax.swing.JButton();
        buttonActualizar = new javax.swing.JButton();
        buttonSimular = new javax.swing.JButton();

        tableOfertas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableOfertas);

        buttonVolver.setText("Volver");
        buttonVolver.addActionListener(this::buttonVolverActionPerformed);

        buttonActualizar.setText("Actualizar");
        buttonActualizar.addActionListener(this::buttonActualizarActionPerformed);

        buttonSimular.setText("Simular Subasta");
        buttonSimular.addActionListener(this::buttonSimularActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonVolver))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonSimular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonActualizar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonActualizar)
                    .addComponent(buttonSimular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(buttonVolver)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActualizarActionPerformed
        // TODO add your handling code here:
        loadTablaOfertas();
    }//GEN-LAST:event_buttonActualizarActionPerformed

    private void buttonSimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimularActionPerformed
        // TODO add your handling code here:
        
        Oferta dataAccess = new Oferta();
        Producto producto = Producto.obtenerPorId(1);
        
        OferenteProcessor_Thread oferente1 = new OferenteProcessor_Thread(dataAccess, producto, Postulante.obtenerPorDni(123));
        OferenteProcessor_Thread oferente2 = new OferenteProcessor_Thread(dataAccess, producto, Postulante.obtenerPorDni(456));
        OferenteProcessor_Thread oferente3 = new OferenteProcessor_Thread(dataAccess, producto, Postulante.obtenerPorDni(789));
        
        oferente1.start();
        oferente2.start();
        oferente3.start();
    }//GEN-LAST:event_buttonSimularActionPerformed

    private void buttonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVolverActionPerformed
        // TODO add your handling code here:
        ventanaPrincipal.mostrarPantalla("menu");
    }//GEN-LAST:event_buttonVolverActionPerformed

    @Override
    public void onShow() {
        loadTablaOfertas();
    }
    
    private void loadTablaOfertas(){
        
        DefaultTableModel modelOfertas = (DefaultTableModel) tableOfertas.getModel();
        
        modelOfertas.setRowCount(0);
        modelOfertas.setColumnCount(0);
        
        modelOfertas.addColumn("postulante");
        modelOfertas.addColumn("producto");
        modelOfertas.addColumn("fecha");
        modelOfertas.addColumn("monto");
        modelOfertas.addColumn("estado");
        
        for(Oferta oferta : Oferta.obtenerTodos()){
            Object[] fila = new Object[5];
            fila[0] = Postulante.obtenerPorDni(oferta.getDniPostulante().getDni());
            fila[1] = Producto.obtenerPorId(oferta.getIdProducto().getId());
            fila[2] = oferta.getFechaCreacion();
            fila[3] = oferta.getMonto();
            fila[4] = oferta.getEstado();
            
            modelOfertas.addRow(fila);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonActualizar;
    private javax.swing.JButton buttonSimular;
    private javax.swing.JButton buttonVolver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableOfertas;
    // End of variables declaration//GEN-END:variables
}
