/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import database.DBConnection;
import database.Oferta;
import java.sql.ResultSet;
import java.awt.CardLayout;
import java.awt.Component;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author ramir
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();

        contenedor.setLayout(new CardLayout());

        contenedor.add(new PantallaOfertas(this), "ofertas");
        contenedor.add(new PantallaMenu(this), "menu");
        contenedor.add(new PantallaListadoOfertas(this), "listadoOfertas");

        mostrarPantalla("menu");
    }

    public void mostrarPantalla(String nombre) {
        CardLayout cl = (CardLayout) contenedor.getLayout();

        cl.show(contenedor, nombre);

        for (Component c : contenedor.getComponents()) {
            if (c.isVisible()) {
                if (c instanceof IPantallaBase iPantallaBase) {
                    iPantallaBase.onShow();
                }
                break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:

        String message = "";

        DBConnection db = new DBConnection();
        
        try {
            ResultSet rs = db.query(
                    "SELECT\n"
                    + "	dniPostulante dni,\n"
                    + "	COUNT(id) cantidadOfertas,\n"
                    + " SUM(CASE estado WHEN 'EXITO' THEN 1 ELSE 0 END) ofertasGanadas,\n"
                    + "	SUM(monto) totalGastado\n"
                    + "FROM `Oferta`\n"
                    + "GROUP BY dniPostulante");
            
            while(rs.next()){
                message += "Postulante " + rs.getInt("dni") 
                        + " ofertas " + rs.getInt("cantidadOfertas") 
                        + " ganadas " + rs.getInt("ofertasGanadas")
                        + " gastado " + rs.getBigDecimal("totalGastado")
                        + "\n";
            }
            message = message == "" ? "no se registraron ofertas" : message;
        } catch (SQLException ex) {
            System.out.println(ex);
        }
        
        JOptionPane jOptionPane1 = new JOptionPane();
        jOptionPane1.showMessageDialog(
                VentanaPrincipal.this,
                message,
                "Cierre de aplicación",
                jOptionPane1.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedor;
    // End of variables declaration//GEN-END:variables
}
